---
title: "Verilen-Alınan Göçler ve Yaş Grupları"
author: 
  - Selin Ertürk[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 21080351

# Giriş
Bu taslak size proje ödevinizi yazarken yardımcı olması amacıyla oluşturulmuştur. Ödevlerinizde, makalelerinizde, sunumlarınızda ve projelerinizde kullandığınız tüm bilgi kaynaklarına atıfta bulunmalısınız. Alıntı ve gönderme yapmak okuyuculara çalışmanızda kullandığınız/başvurduğunuz  kaynaklara ulaşma imkanı sağlar. **Her ne kadar kendi sözlerinizi kullanıyor olsanız da, başkalarına ait fikirleri çalışmanızda aktarıyorsanız bu fikirlerin kaynağını belgelemek zorundasınız. Aksi takdirde akademik intihal yapmış olursunuz.** Yazım konusunda @aydinonat:2007'ye başvurabilirsiniz. 


Proje ödevinizde yer alan başlıkların bu metinde yer alan başlıkları kesinlikle içermesi gerekmektedir. Burada kullanılan başlıklar haricinde farklı alt başlıklar da kullanabilirsiniz. Projenizi yazarken bu dosyayı taslak olarak kullanıp içeriğini projenize uyarlayınız.

## Çalışmanın Amacı
 Göç savaş, hastalık, ekonomik buhran, toplum düzeni bozulması gibi durumlarda bireylerin, ailelerin ya da
toplumların bulundukları bölgeyi terk ederek yeni bir yaşam alanına taşınması durumudur.Göçleri iç ve dış göç olmak üzere iki başlıkta ele alırız. İç göç doğal afetler, nüfus ve yatırımlarda dengesiz dağılım, iş imkanları gibi etkilerle gerçekleşir.Dış göçe etki eden önemli sebepler ise baskı, zulüm, ekonomik krizler gibi hayatı uzun dönemde önemli derecede etkileyecek sorunlardır.Bununla birlikte dış göçte beyin göçü de önemli bir paya sahiptir.Eğitim için yurdun terkedilmesinin nedeni yurt dışının daha avantajlı fırsatlar sunmasıdır.Bu da temelde ülkenin bazı konularda diğer ülkelerden geri kaldığının göstergesidir.Yani özetle ülkenin bulunduğu şartların kötü durumda olması,diğer ülkelerden geride kalmış olması göçlerin ana sebebidir.
 Verilen göçlerin fazlalığı o ülkenin durumu için iyi sinyaller vermezken alınan göçlerin fazlalığı ülkenin durumu için iyi sinyaller sunar.Bu durumdan yola çıkarak verilen göçlerin alınan göçten fazla olması ülkenin durumunda iyileştirilmesi gereken durumlar olduğu sonucunu doğurur.Ülke nüfusunun azalarak dış ülklerden gelen nüfusun artması da siyasi ve politik alanlarda da sonuç doğuracaktır.Yani her durumda göçler ülkeler için çok önemli bir inceleme alanıdır.
 Çalışmamda incelemek istediğim durum ise bu durumun hangi etkenlerle etkileşimde olduğudur.Veri setim verilen ve alınan göçlerin yaş gruplarına göre düzeyini gösteriyor.Yanıtlamaka istediğim sorular ;verilen göçler alınan göçleri etkiler mi, yaş gruplarına göre verilen göçler diğer yaş grupları üzerinde belirleyici midir,hangi yaş grupları göçlerde daha etkilidir, hangi yaş grupları ülkenin durumlarından daha fazla etkilenir.

## Literatür 
Bu bölümde konu ile ilgili olarak okuduğunuz makaleleri referans vererek tartışınız. **Her makaleyi ayrı başlık altında tek tek özetlemeyiniz.** Literatür taramasında **en az altı** makaleye atıf yapılması ve bu makalelerden **en az ikisinin İngilizce** olması gerekmektedir.


**_Taslakta bu cümleden sonra yer alan hiçbir şey silinmemelidir._**

\newpage
# Kaynakça {#references}
<div id="refs"></div>

